from enum import IntEnum, Enum


class Operation(IntEnum):
    HANDSHAKE = 0
    HANDSHAKE_REPLY = 1
    HEARTBEAT = 2
    HEARTBEAT_REPLY = 3
    SEND_MSG = 4
    SEND_MSG_REPLY = 5
    DISCONNECT_REPLY = 6
    AUTH = 7
    AUTH_REPLY = 8
    RAW = 9
    PROTO_READY = 10
    PROTO_FINISH = 11
    CHANGE_ROOM = 12
    CHANGE_ROOM_REPLY = 13
    REGISTER = 14
    REGISTER_REPLY = 15
    UNREGISTER = 16
    UNREGISTER_REPLY = 17
    # B 站业务自定义 OP
    # MinBusinessOp = 1000
    # MaxBusinessOp = 10000

    def __repr__(self):
        return f'<{self.__class__.__name__}.{self.name}>'


class CommandMsg(Enum):
    """websocket 中接收到的 command"""
    # 弹幕消息
    DANMU_MSG = 'DANMU_MSG'
    # 有人送礼
    SEND_GIFT = 'SEND_GIFT'
    # 有人上舰
    GUARD_BUY = 'GUARD_BUY'
    ACTIVITY_BANNER_RED_NOTICE_CLOSE = 'ACTIVITY_BANNER_RED_NOTICE_CLOSE'
    ACTIVITY_BANNER_UPDATE_V2 = 'ACTIVITY_BANNER_UPDATE_V2'
    ACTIVITY_MATCH_GIFT = 'ACTIVITY_MATCH_GIFT'
    ACTIVITY_RED_PACKET = 'ACTIVITY_RED_PACKET'
    BLOCK = 'BLOCK'
    CHANGE_ROOM_INFO = 'CHANGE_ROOM_INFO'
    CLOSE = 'CLOSE'
    COMBO_END = 'COMBO_END'
    COMBO_SEND = 'COMBO_SEND'
    CUT_OFF = 'CUT_OFF'
    DAILY_QUEST_NEWDAY = 'DAILY_QUEST_NEWDAY'
    END = 'END'
    ENTRY_EFFECT = 'ENTRY_EFFECT'
    GUARD_LOTTERY_START = 'GUARD_LOTTERY_START'
    GUARD_MSG = 'GUARD_MSG'
    GUIARD_MSG = 'GUIARD_MSG'
    HOUR_RANK_AWARDS = 'HOUR_RANK_AWARDS'
    LIVE = 'LIVE'
    LOL_ACTIVITY = 'LOL_ACTIVITY'
    LUCK_GIFT_AWARD_USER = 'LUCK_GIFT_AWARD_USER'
    MESSAGEBOX_USER_GAIN_MEDAL = 'MESSAGEBOX_USER_GAIN_MEDAL'
    NOTICE_MSG = 'NOTICE_MSG'
    PK_AGAIN = 'PK_AGAIN'
    PK_END = 'PK_END'
    PK_MATCH = 'PK_MATCH'
    PK_MIC_END = 'PK_MIC_END'
    PK_PRE = 'PK_PRE'
    PK_PROCESS = 'PK_PROCESS'
    PK_SETTLE = 'PK_SETTLE'
    PK_START = 'PK_START'
    PREPARING = 'PREPARING'
    RAFFLE_END = 'RAFFLE_END'
    RAFFLE_START = 'RAFFLE_START'
    REFRESH = 'REFRESH'
    ROOM_BLOCK_INTO = 'ROOM_BLOCK_INTO'
    ROOM_BLOCK_MSG = 'ROOM_BLOCK_MSG'
    ROOM_BOX_MASTER = 'ROOM_BOX_MASTER'
    ROOM_KICKOUT = 'ROOM_KICKOUT'
    ROOM_LIMIT = 'ROOM_LIMIT'
    ROOM_LOCK = 'ROOM_LOCK'
    ROOM_RANK = 'ROOM_RANK'
    ROOM_REAL_TIME_MESSAGE_UPDATE = 'ROOM_REAL_TIME_MESSAGE_UPDATE'
    ROOM_REFRESH = 'ROOM_REFRESH'
    ROOM_SHIELD = 'ROOM_SHIELD'
    ROOM_SILENT_OFF = 'ROOM_SILENT_OFF'
    ROOM_SILENT_ON = 'ROOM_SILENT_ON'
    ROOM_SKIN_MSG = 'ROOM_SKIN_MSG'
    ROUND = 'ROUND'
    SCORE_CARD = 'SCORE_CARD'
    SEND_TOP = 'SEND_TOP'
    SPECIAL_GIFT = 'SPECIAL_GIFT'
    SYS_GIFT = 'SYS_GIFT'
    SYS_MSG = 'SYS_MSG'
    TV_END = 'TV_END'
    TV_START = 'TV_START'
    USER_TOAST_MSG = 'USER_TOAST_MSG'
    WARNING = 'WARNING'
    WEEK_STAR_CLOCK = 'WEEK_STAR_CLOCK'
    # 欢迎消息, 年费老爷, 月费老爷之类
    WELCOME = 'WELCOME'
    WELCOME_GUARD = 'WELCOME_GUARD'
    WIN_ACTIVITY = 'WIN_ACTIVITY'
    WISH_BOTTLE = 'WISH_BOTTLE'

    def __repr__(self):
        return f'<{self.__class__.__name__}.{self.name}>'
